permalink: /:year:month:day/:title
url: "https://tooopen.github.io/"
baseurl: ""

# variables
name: CorderClown
description: Corder + Clown = CorderClown
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

plugins:
  - jemoji

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true